[package]
name = "dice-parser"
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-only"
description = "A parser and roller for standard RPG dice notation."
repository = "https://github.com/marcell-ziegler/dice-parser"
readme = "README.md"
keywords = ["dice", "rpg", "parser", "roller", "tabletop"]
categories = ["games", "parsing"]
exclude = [".github/"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
rand = "0.9.2"
